services:
  sql-backend:
    image: mysql:oraclelinux9
    ports:
      - 8080:3306
    container_name: sql-backend
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  application-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense_backend_service
    ports:
      - 8000:8000
    working_dir: /app/backend
    command: uvicorn server:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app


  application-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense_frontend_service
    ports:
      - 8501:8501
    working_dir: /app/frontend
    command: streamlit run app.py
    volumes:
      - .:/app

volumes:
  db_data:
  backend_db:
  frontend_db:
